version: '3.0'

services:
  jupyter_notebook:
    image: jupyter/minimal-notebook:python-3.8.8
    container_name: jupyter_notebook
    user: root
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/work
      - ./configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - etl_network
  postgres:
    image: bitnami/postgresql:12
    container_name: postgres
    restart: always
    environment:
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./create_staging.sh:/docker-entrypoint-initdb.d/create_staging.sh

volumes:
  db_volume:
    driver: local
networks:
  etl_network: null